const data = window.NAIROBI_PIXEL_DATA;
const app = document.getElementById('app');

const safeWa = (label) => `${data.links.whatsapp}?text=${encodeURIComponent(`Hi NairobiPixel, I'm interested in the ${label} package.`)}`;

function fallbackImage(path, alt) {
  return `<div class="image-wrap reveal"><img src="${path}" alt="${alt}" loading="lazy" onerror="this.closest('.image-wrap').classList.add('missing');this.style.display='none';this.closest('.image-wrap').querySelector('.missing-note').textContent='Missing image: ${path}'"><div class="missing-note"></div></div>`;
}

app.innerHTML = `
<section class="hero section-dark" id="home"><div class="container hero-grid"><div class="reveal"><p class="kicker">DIGITAL GROWTH SYSTEMS</p><h1>We Build Digital <span>Growth Systems</span> That Help Businesses Get Leads, Sell & Scale.</h1><p class="sub">Websites, ordering systems, dashboards, automation and content systems built for modern Kenyan businesses.</p><div class="actions"><a class="btn btn-gold shimmer" href="#portfolio">View Our Portfolio</a><a class="btn btn-dark" href="${data.links.whatsapp}" target="_blank" rel="noreferrer">Get Your System Built</a></div><ul class="trust-points"><li>Modern Systems</li><li>Mobile First</li><li>Fast Delivery</li><li>Made in Kenya</li></ul></div><div class="hero-visual"><div class="float-card laptop">${fallbackImage('assets/portfolio/eastleigh/hero-desktop.png','Eastleigh preview')}</div><div class="float-card phone">${fallbackImage('assets/portfolio/beirut-delivery/menu-mobile.png','Beirut preview')}</div><div class="float-card panel">${fallbackImage('assets/portfolio/beirut-jiko/dashboard-home.png','Dashboard preview')}</div></div></div></section>
<section class="trusted"><div class="container"><p class="kicker center">TRUSTED BY BUSINESSES</p><div class="trusted-row">${data.trustedBusinesses.map(x => `<span>${x}</span>`).join('')}</div></div></section>
<section id="services" class="section-light"><div class="container"><p class="kicker center">WHAT WE BUILD</p><h2>Digital Systems That Power Your Business <span>Growth</span></h2><div class="service-grid">${data.services.map(s => `<article class='reveal'><i>${s[2]}</i><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div></div></section>
<section id="portfolio" class="section-dark"><div class="container"><p class="kicker center">FEATURED PROJECTS</p><h2>Systems We've Built</h2><div class="project-grid">${data.projects.map(p => `<article class='project reveal'>${fallbackImage(p.image,p.name)}<div class='body'><h3>${p.name}</h3><p class='cat'>${p.category}</p><p>${p.description}</p><div class='row'><a class='btn btn-gold' href='${p.live}' target='_blank' rel='noreferrer'>View Live</a><a class='btn btn-ghost' href='${data.links.whatsapp}' target='_blank' rel='noreferrer'>Case Study</a></div></div></article>`).join('')}</div></div></section>
<section class="section-light"><div class="container"><p class="kicker center">CASE STUDIES</p><h2>Real Results For Real Businesses</h2><div class="case-list">${data.caseStudies.map(c => `<article class='reveal'>${fallbackImage(c.image,c.title)}<div><h3>${c.title}</h3><p><strong>Challenge:</strong> ${c.challenge}</p><p><strong>Solution:</strong> ${c.solution}</p><p><strong>Result:</strong> ${c.result}</p><a href='${data.links.whatsapp}' target='_blank' rel='noreferrer'>Read Full Case Study →</a></div></article>`).join('')}</div></div></section>
<section id="packages" class="section-dark"><div class="container"><p class="kicker center">PACKAGES & PRICING</p><h2>Simple Packages. <span>Real Value.</span></h2><div class="price-grid">${data.pricing.map(p => `<article class='reveal'><p class='pack-ico'>${p.icon}</p><h3>${p.name}</h3><p class='price'>${p.price}</p><ul>${p.items.map(i => `<li>${i}</li>`).join('')}</ul><a class='btn btn-gold shimmer' href='${safeWa(p.name)}' target='_blank' rel='noreferrer'>Get Started</a></article>`).join('')}</div><p class='helper-note'>All packages are flexible. Let’s discuss what your business needs.</p></div></section>
<section class="section-light" id="about"><div class="container"><p class="kicker">SOCIAL PROOF</p><h2>Growth We've Helped Create</h2><div class='social-wrap'><div class="stats">${data.stats.map(s => `<article class='reveal'><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</div><div class='social-visual reveal'>${fallbackImage('assets/portfolio/social-growth/instagram-grid.png','Social media grid')}<div class='mini-cards'>${data.analytics.map(a=>`<article><h4>${a[0]}</h4><p>${a[1]}</p></article>`).join('')}<article><h4>Analytics</h4><div class='chart'></div></article></div></div></div></div></section>
<section id="process" class="section-dark"><div class="container"><p class="kicker center">OUR PROCESS</p><h2>Simple Process. <span>Big Results.</span></h2><div class='timeline'>${data.timeline.map(t => `<article class='reveal'><span>${t[0]}</span><h3>${t[1]}</h3><p>${t[2]}</p></article>`).join('')}</div></div></section>
<section class="cta-band"><div class="container cta-wrap"><div><h2>Ready To Build Your Digital Growth System?</h2><p>Let’s build a system that gets you leads, sales and growth on autopilot.</p></div><div class='actions'><a class='btn btn-light shimmer' href='${data.links.whatsapp}' target='_blank' rel='noreferrer'>Chat on WhatsApp</a><a class='btn btn-dark' href='${data.links.whatsapp}' target='_blank' rel='noreferrer'>Book a Free Strategy Call</a></div></div></section>
<footer id="contact"><div class="container footer"><div><img src="assets/brand/nairobipixel-logo.jpg" alt="NairobiPixel logo" /><p>Building digital systems that help businesses grow.</p></div><div><h4>Quick Links</h4>${data.nav.map(x=>`<a href='#${x.toLowerCase()==='home'?'home':x.toLowerCase()}'>${x}</a>`).join('')}</div><div><h4>Services</h4><p>Websites</p><p>Ordering Systems</p><p>Dashboards</p><p>Ecommerce</p><p>Automation</p><p>Real Estate Platforms</p><p>Social Media Growth</p></div><div><h4>Contact</h4><p>0700 370 377</p><p>Nairobi, Kenya</p><a href='${data.links.whatsapp}' target='_blank' rel='noreferrer'>WhatsApp</a></div></div><div class='copy'>© 2026 NairobiPixel. All Rights Reserved.</div></footer>`;

const toggle = document.querySelector('.menu-toggle'); const drawer = document.querySelector('.mobile-drawer'); const backdrop = document.querySelector('.mobile-backdrop');
const closeBtn = document.querySelector('.menu-close');
const close = () => { drawer.classList.remove('open'); backdrop.classList.remove('show'); toggle.setAttribute('aria-expanded', 'false'); document.body.classList.remove('no-scroll'); };
const open = () => { drawer.classList.add('open'); backdrop.classList.add('show'); toggle.setAttribute('aria-expanded', 'true'); document.body.classList.add('no-scroll'); };
toggle.addEventListener('click', () => drawer.classList.contains('open') ? close() : open()); closeBtn.addEventListener('click', close);
backdrop.addEventListener('click', close); document.addEventListener('keydown', e => e.key === 'Escape' && close());
document.querySelectorAll('.mobile-drawer a, a[href^="#"]').forEach(a => a.addEventListener('click', close));

if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
  const io = new IntersectionObserver((entries) => entries.forEach(e => e.isIntersecting && e.target.classList.add('in')), { threshold: 0.15 });
  document.querySelectorAll('.reveal').forEach(el => io.observe(el));
}
